services:
  master-web:
    container_name: master-web
    image: master-web:1.0.0
    build:
      context: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: Asia/Jakarta
    restart: always
    networks:
      - shared-networks

networks:
  shared-networks:
    name: shared-networks
    external: true
